src/Linkbot.Web/Pages/Customers/CreateModal.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Linkbot.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Volo.Abp.AspNetCore.Mvc.UI.Alerts;
using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Form;
using Volo.Abp.Data;
using Volo.Abp.ObjectExtending;

namespace Linkbot.Web.Pages.Customers
{
    public class CreateModalModel : LinkbotPageModel
    {
        [BindProperty]
        public CustomerDetailsModel CustomerDetails { get; set; }

        public List<SelectListItem> CustomerStatusList { get; set; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "NEW LEAD", Text = "New Lead"},
            new SelectListItem { Value = "CUSTOMER", Text = "Customer"},
            new SelectListItem { Value = "VIP", Text = "VIP"},
            new SelectListItem { Value = "VVIP", Text = "VVIP"},
            new SelectListItem { Value = "INACTIVE", Text = "Inactive"}
        };

        public List<SelectListItem> SubscriptionList { get; set; } = new List<SelectListItem>
        {
            new SelectListItem { Value = "NEW", Text = "New"},
            new SelectListItem { Value = "SUBSCRIBED", Text = "Subscribed"},
            new SelectListItem { Value = "UNSUBSCRIBED", Text = "Unsubscribed"}
        };

        public bool IsEmailMandatory { get; set; }
        public bool IsMobileNoMandatory { get; set; }

        private readonly ICustomerDetailsAppService _customerDetailsAppService;
        private readonly ICustomerSettingsAppService _customerSettingsAppService;
        private readonly ICustomerCustomPropertyAppService _customerCustomPropertyAppService;

        public CreateModalModel(ICustomerDetailsAppService customerDetailsAppService
            , ICustomerSettingsAppService customerSettingsAppService
            , ICustomerCustomPropertyAppService customerCustomPropertyAppService)
        {
            _customerDetailsAppService = customerDetailsAppService;
            _customerSettingsAppService = customerSettingsAppService;
            _customerCustomPropertyAppService = customerCustomPropertyAppService;
        }

        public void OnGet()
        {
            CustomerDetails = new CustomerDetailsModel();
            var customPropertyList = _customerCustomPropertyAppService.GetCustomerCustomPropertyAsync().Result;
            var customerSettingsDto = _customerSettingsAppService.GetCustomerSettingsAsync().Result;

            if (customerSettingsDto.IsEmailMandatory)
                IsEmailMandatory = true;

            if(customerSettingsDto.IsMobileNumberMandatory)
                IsMobileNoMandatory = true;

            CustomerDetails.CustomExtraPropertySetting = customPropertyList;
            foreach (var customProperty in customPropertyList)
            {
                if(customProperty.CustomPropertyType == "string")
                    CustomerDetails.ExtraProperties.Add(customProperty.CustomPropertyName, "");
                else if (customProperty.CustomPropertyType == "int")
                    CustomerDetails.ExtraProperties.Add(customProperty.CustomPropertyName, 0);
                else if (customProperty.CustomPropertyType == "bool")
                    CustomerDetails.ExtraProperties.Add(customProperty.CustomPropertyName, false);
                else if (customProperty.CustomPropertyType == "datetime")
                    CustomerDetails.ExtraProperties.Add(customProperty.CustomPropertyName, DateTime.Today);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var createUpdateCustomerDetailsDto = ObjectMapper.Map<CustomerDetailsModel, CreateUpdateCustomerDetailsDto>(CustomerDetails);

            //var customerSettingsDto = await _customerSettingsAppService.GetCustomerSettingsAsync();
            //createUpdateCustomerDetailsDto.IsEmailMandatory = customerSettingsDto.IsEmailMandatory;
            //createUpdateCustomerDetailsDto.IsMobileNumberMandatory = customerSettingsDto.IsMobileNumberMandatory;

            await _customerDetailsAppService.CreateAsync(createUpdateCustomerDetailsDto);
            return NoContent();
        }

        [AutoMap(typeof(CreateUpdateCustomerDetailsDto), ReverseMap = true)]
        public class CustomerDetailsModel: ExtensibleObject
        {
            [StringLength(128)]
            public string FirstName { get; set; }

            [StringLength(128)]
            public string LastName { get; set; }

            [RegularExpression(@"\d{8}$", ErrorMessage = "Invalid contact number.")]
            public string PhoneNumber { get; set; }

            [RegularExpression(@"\d{8}$", ErrorMessage = "Invalid contact number.")]
            public string MobileNumber { get; set; }

            [EmailAddress]
            public string EmailAddress { get; set; }

            public string AddressLine1 { get; set; }

            public string AddressLine2 { get; set; }

            [Range(0, Int64.MaxValue, ErrorMessage = "Invalid postal code.")]
            [StringLength(6)]
            public string PostalCode { get; set; }

            public string CompanyName { get; set; }

            [SelectItems(nameof(CustomerStatusList))]
            public string CustomerStatus { get; set; }


            [SelectItems(nameof(SubscriptionList))]
            public string Subscription { get; set; }

            [TextArea(Rows = 4)]
            public string Remark { get; set; }

            public List<CreateUpdateCustomPropertyDetailsDto> CustomExtraPropertySetting { get; set; }

        }
    }
    
}

src/Linkbot.Web/Pages/Customers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Linkbot.Customers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Volo.Abp;

namespace Linkbot.Web.Pages.Customers
{
    public class IndexModel : LinkbotPageModel
    {
        private readonly ICustomerDetailsAppService _customerDetailsAppService;
        private readonly ICustomerSettingsAppService _customerSettingsAppService;
        private readonly ICustomerCustomPropertyAppService _customerCustomPropertyAppService;

        [BindProperty]
        public string Filter { get; set; }

        [BindProperty]
        public string FilterHidden { get; set; }

        public IndexModel(ICustomerDetailsAppService customerDetailsAppService
            , ICustomerSettingsAppService customerSettingsAppService
            , ICustomerCustomPropertyAppService customerCustomPropertysAppService)
        {
            _customerDetailsAppService = customerDetailsAppService;
            _customerSettingsAppService = customerSettingsAppService;
            _customerCustomPropertyAppService = customerCustomPropertysAppService;
        }

        #region Import/Export Excel
        public async Task<IActionResult> OnPostExportAsync()
        {
            try
            {
                var customers = await _customerDetailsAppService.GetListExportAsync(new PageLookupInputDto()
                {
                    Filter = FilterHidden
                }); ;

                var customPropertyList = await _customerCustomPropertyAppService.GetCustomerCustomPropertyAsync();

                var memoryStream = new MemoryStream();
                using (var workbook = new XLWorkbook())
                {
                    Dictionary<string, int> customDic = new Dictionary<string, int>();
                    var worksheet = workbook.Worksheets.Add("Customers Sheet");

                    var firstName = worksheet.Cell(1, 1);
                    var lastName = worksheet.Cell(1, 2);
                    var phoneNumber = worksheet.Cell(1, 3);
                    var email = worksheet.Cell(1, 4);
                    var customerStatus = worksheet.Cell(1, 5);
                    var substription = worksheet.Cell(1, 6);
                    var mobileNumber = worksheet.Cell(1, 7);
                    var addressLine1 = worksheet.Cell(1, 8);
                    var addressLine2 = worksheet.Cell(1, 9);
                    var postalCode = worksheet.Cell(1, 10);
                    var companyName = worksheet.Cell(1, 11);
                    var remark = worksheet.Cell(1, 12);

                    for (var i = 0; i < customPropertyList.Count; i++)
                    {
                        customDic.Add(customPropertyList[i].CustomPropertyName, 13 + i);
                        worksheet.Cell(1, 13 + i).Value = customPropertyList[i].CustomPropertyName;
                        worksheet.Cell(1, 13 + i).Style.Font.Bold = true;
                    }

                    firstName.Value = "First name";
                    firstName.Style.Font.Bold = true;
                    lastName.Value = "Last name";
                    lastName.Style.Font.Bold = true;
                    phoneNumber.Value = "Phone No.";
                    phoneNumber.Style.Font.Bold = true;
                    email.Value = "Email address";
                    email.Style.Font.Bold = true;
                    customerStatus.Value = "Status";
                    customerStatus.Style.Font.Bold = true;
                    substription.Value = "Substription";
                    substription.Style.Font.Bold = true;
                    mobileNumber.Value = "Mobile";
                    mobileNumber.Style.Font.Bold = true;
                    addressLine1.Value = "Address 1";
                    addressLine1.Style.Font.Bold = true;
                    addressLine2.Value = "Address 2";
                    addressLine2.Style.Font.Bold = true;
                    postalCode.Value = "PostalCode";
                    postalCode.Style.Font.Bold = true;
                    companyName.Value = "Company Name";
                    companyName.Style.Font.Bold = true;
                    remark.Value = "Remark";
                    remark.Style.Font.Bold = true;

                    for (var i = 0; i < customers.Count; i++)
                    {
                        var customer = customers[i];

                        worksheet.Cell(i + 2, 1).Value = customer.FirstName;
                        worksheet.Cell(i + 2, 2).Value = customer.LastName;
                        worksheet.Cell(i + 2, 3).Value = customer.PhoneNumber;
                        worksheet.Cell(i + 2, 4).Value = customer.EmailAddress;
                        worksheet.Cell(i + 2, 5).Value = customer.CustomerStatus;
                        worksheet.Cell(i + 2, 6).Value = customer.Subscription;
                        worksheet.Cell(i + 2, 7).Value = customer.MobileNumber;
                        worksheet.Cell(i + 2, 8).Value = customer.AddressLine1;
                        worksheet.Cell(i + 2, 9).Value = customer.AddressLine2;
                        worksheet.Cell(i + 2, 10).Value = customer.PostalCode;
                        worksheet.Cell(i + 2, 11).Value = customer.CompanyName;
                        worksheet.Cell(i + 2, 12).Value = customer.Remark;

                        foreach (var customProperty in customPropertyList)
                        {
                            customDic.TryGetValue(customProperty.CustomPropertyName, out int cellColumn);
                            customer.ExtraProperties.TryGetValue(customProperty.CustomPropertyName, out object extraValue);

                            if (extraValue != null)
                                worksheet.Cell(i + 2, cellColumn).Value = extraValue;
                        }
                    }
                    workbook.SaveAs(memoryStream);
                }
              
                memoryStream.Position = 0;
                return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Customer.xlsx");
            }
            catch(Exception ex)
            {
                Logger.LogError($"Unexpected Error When Export Customer: {ex.Message}");
                Alerts.Warning("Unexpected Error While Export Customer Details");

                return await Task.FromResult<IActionResult>(Page());
            }
        }

        public async Task<IActionResult> OnPostImportAsync(IFormFile excel)
        {
            if (excel == null)
            {
                return await Task.FromResult<IActionResult>(Page());
            }

            using (var workbook = new XLWorkbook(excel.OpenReadStream()))
            {
                var worksheet = workbook.Worksheet("Customers Sheet");

                var count = 0;
                var errorRow = "";
                foreach (var row in worksheet.Rows())
                {
                    CreateUpdateCustomerDetailsDto input;
                    count += 1;
                    if (count > 1) //skip the first row.
                    {
                        input = new CreateUpdateCustomerDetailsDto()
                        {
                            FirstName = row.Cell(1).Value.ToString() == "" ? null : row.Cell(1).Value.ToString(),
                            LastName = row.Cell(2).Value.ToString() == "" ? null : row.Cell(2).Value.ToString(),
                            PhoneNumber = row.Cell(3).Value.ToString() == "" ? null : row.Cell(3).Value.ToString(),
                            EmailAddress = row.Cell(4).Value.ToString() == "" ? null : row.Cell(4).Value.ToString(),
                            CustomerStatus = row.Cell(5).Value.ToString() == "" ? null : row.Cell(5).Value.ToString(),
                            Subscription = row.Cell(6).Value.ToString() == "" ? null : row.Cell(6).Value.ToString(),
                            MobileNumber = row.Cell(7).Value.ToString() == "" ? null : row.Cell(7).Value.ToString(),
                            AddressLine1 = row.Cell(8).Value.ToString() == "" ? null : row.Cell(8).Value.ToString(),
                            AddressLine2 = row.Cell(9).Value.ToString() == "" ? null : row.Cell(9).Value.ToString(),
                            PostalCode = row.Cell(10).Value.ToString() == "" ? null : row.Cell(10).Value.ToString(),
                            CompanyName = row.Cell(11).Value.ToString() == "" ? null : row.Cell(11).Value.ToString(),
                            Remark = row.Cell(12).Value.ToString() == "" ? null : row.Cell(12).Value.ToString(),
                        };

                        var customPropertyList = _customerCustomPropertyAppService.GetCustomerCustomPropertyAsync().Result;

                        for (var i = 0; i < customPropertyList.Count; i++)
                        {
                            input.ExtraProperties.Add(worksheet.Row(1).Cell(13 + i).Value.ToString(), row.Cell(13 + i).Value.ToString());
                        }

                        try
                        {
                            var customerSettingsDto = await _customerSettingsAppService.GetCustomerSettingsAsync();

                            if ((customerSettingsDto.IsEmailMandatory && string.IsNullOrEmpty(input.EmailAddress)) ||
                                (customerSettingsDto.IsMobileNumberMandatory && string.IsNullOrEmpty(input.MobileNumber)))
                            {
                                if (errorRow == "")
                                    errorRow += count;
                                else
                                    errorRow += ", " + count;
                            }
                            else
                                await _customerDetailsAppService.CreateAsync(input);

src/Linkbot.Web/Pages/Customers/Setting/EditModal.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Linkbot.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Linkbot.Web.Pages.Customers.Setting
{
    public class EditModalModel : LinkbotPageModel
    {
        [BindProperty]
        public CreateUpdateCustomerSettingsDto CustomerSettings { get; set; }

        private readonly ICustomerSettingsAppService _customerSettingsAppService;

        public EditModalModel(ICustomerSettingsAppService customerSettingsAppService)
        {
            _customerSettingsAppService = customerSettingsAppService;
        }

        public async Task OnGetAsync()
        {
            var customerSettingsDto = await _customerSettingsAppService.GetCustomerSettingsAsync();
            CustomerSettings = ObjectMapper.Map<CustomerSettingsDto, CreateUpdateCustomerSettingsDto>(customerSettingsDto);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _customerSettingsAppService.UpdateCustomerSettingsAsync(CustomerSettings);
            return NoContent();
        }
    }
}

src/Linkbot.Web/Pages/Customers/CreateModal.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Linkbot.Localization
@using Linkbot.Web.Pages.Customers
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Volo.Abp.ObjectExtending
@using Volo.Abp.Data
@using Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Themes.Basic.Components.PageAlerts
@model CreateModalModel
@inject IStringLocalizer<LinkbotResource> L
@inject IStringLocalizerFactory StringLocalizerFactory
@{
    Layout = null;
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#customerDetailsCreateForm").submit(function () {
            var errorTab = $("#customerDetailsCreateForm .input-validation-error").closest(".tab-pane");
            if (errorTab.length !== 0) {
                var tabId = errorTab.get(0).id;
                $('#customerDetailsCreateForm a[href="#' + tabId + '"]').tab('show');
            };
        });
    });
</script>

<form method="post" asp-page="/Customers/CreateModal" id="customerDetailsCreateForm">
    <abp-modal size="Large">
        <abp-modal-header title="@L["NewCustomer"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-tabs name="create-user-modal-tabs">
                <abp-tab title="@L["BasicInformations"].Value">
                    <abp-input asp-for="CustomerDetails.FirstName" />
                    <abp-input asp-for="CustomerDetails.LastName" />
                    @if (Model.IsEmailMandatory)
                    {
                        <abp-input asp-for="CustomerDetails.EmailAddress" required-symbols="true" data-val="true" data-val-required="The Email Address field is required." />
                    }
                    else
                    {
                        <abp-input asp-for="CustomerDetails.EmailAddress" />
                    }

                    @if (Model.IsMobileNoMandatory)
                    {
                        <abp-input asp-for="CustomerDetails.MobileNumber" required-symbols="true" data-val="true" data-val-required="The Mobile Number field is required." />
                    }
                    else
                    {
                        <abp-input asp-for="CustomerDetails.MobileNumber" />
                    }

                    <abp-input asp-for="CustomerDetails.PhoneNumber" />
                    <abp-input asp-for="CustomerDetails.AddressLine1" />
                    <abp-input asp-for="CustomerDetails.AddressLine2" />
                    <abp-input asp-for="CustomerDetails.PostalCode" />
                    <abp-input asp-for="CustomerDetails.CompanyName" />
                </abp-tab>
                <abp-tab title="@L["Status"].Value">
                    <abp-select asp-for="CustomerDetails.CustomerStatus" />
                    <abp-select asp-for="CustomerDetails.Subscription" />
                    <abp-input asp-for="CustomerDetails.Remark" />
                </abp-tab>
                <abp-tab title="@L["Other"].Value">
                    @foreach (var propertyInfo in @Model.CustomerDetails.CustomExtraPropertySetting)
                    {
                        var inputType = String.Empty;
                        var inputFormat = String.Empty;

                        if (@propertyInfo.CustomPropertyType == "datetime")
                        {
                            inputType = "datetime-local";
                            inputFormat = "{0:yyyy-MM-ddTHH:mm}";

                            <abp-input type="@inputType" asp-format="@inputFormat" label="@L[propertyInfo.CustomPropertyName].Value"
                                       asp-for="CustomerDetails.ExtraProperties[propertyInfo.CustomPropertyName]"
                                       value="@String.Format(inputFormat, @Model.CustomerDetails.GetProperty(propertyInfo.CustomPropertyName))" />
                        }
                        else if(@propertyInfo.CustomPropertyType == "bool")
                        {
                            inputType = "checkbox";

                            <abp-input type="@inputType" asp-format="@inputFormat" label="@L[propertyInfo.CustomPropertyName].Value"
                                       asp-for="CustomerDetails.ExtraProperties[propertyInfo.CustomPropertyName]"/>
                        }
                        else
                        {
                        if (@propertyInfo.CustomPropertyType == "string")
                        inputType = "text";
                        else if (@propertyInfo.CustomPropertyType == "int")
                        inputType = "number";

                        <abp-input type="@inputType" asp-format="@inputFormat" label="@L[propertyInfo.CustomPropertyName].Value"
                                   asp-for="CustomerDetails.ExtraProperties[propertyInfo.CustomPropertyName]"
                                   value="@Model.CustomerDetails.GetProperty(propertyInfo.CustomPropertyName)" />
                        }
                    }
                </abp-tab>
            </abp-tabs>
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</form>

src/Linkbot.Web/Pages/Customers/EditModal.cshtml
@page
@using Microsoft.AspNetCore.Mvc.Localization
@using Linkbot.Localization
@using Linkbot.Web.Pages.Customers
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Volo.Abp.ObjectExtending
@using Volo.Abp.Data
@using Volo.Abp.AspNetCore.Mvc.UI.Theme.Basic.Themes.Basic.Components.PageAlerts
@model EditModalModel
@inject IStringLocalizer<LinkbotResource> L
@{
    Layout = null;
}

<script type="text/javascript">
    $(document).ready(function () {
        $("#customerDetailsCreateForm").submit(function () {
            var errorTab = $("#customerDetailsCreateForm .input-validation-error").closest(".tab-pane");
            if (errorTab.length !== 0) {
                var tabId = errorTab.get(0).id;
                $('#customerDetailsCreateForm a[href="#' + tabId + '"]').tab('show');
            };
        });
    });
</script>

<form method="post" asp-page="/Customers/EditModal" id="customerDetailsEditForm">
    <abp-modal size="Large">
        <abp-modal-header title="@L["UpdateCustomer"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-tabs name="edit-user-modal-tabs">
                <abp-tab title="@L["BasicInformations"].Value">
                    <input asp-for="CustomerDetails.Id" />
                    <abp-input asp-for="CustomerDetails.FirstName" />
                    <abp-input asp-for="CustomerDetails.LastName" />
                    @if (Model.IsEmailMandatory)
                    {
                        <abp-input asp-for="CustomerDetails.EmailAddress" required-symbols="true" data-val="true" data-val-required="The Email Address field is required." auto-focus="true" />
                    }
                    else
                    {
                        <abp-input asp-for="CustomerDetails.EmailAddress" />
                    }

                    @if (Model.IsMobileNoMandatory)
                    {
                        <abp-input asp-for="CustomerDetails.MobileNumber" required-symbols="true" data-val="true" data-val-required="The Mobile Number field is required." />
                    }
                    else
                    {
                        <abp-input asp-for="CustomerDetails.MobileNumber" />
                    }

                    <abp-input asp-for="CustomerDetails.PhoneNumber" />
                    <abp-input asp-for="CustomerDetails.AddressLine1" />
                    <abp-input asp-for="CustomerDetails.AddressLine2" />
                    <abp-input asp-for="CustomerDetails.PostalCode" />
                    <abp-input asp-for="CustomerDetails.CompanyName" />
                </abp-tab>
                <abp-tab title="@L["Status"].Value">
                    <abp-select asp-for="CustomerDetails.CustomerStatus" />
                    <abp-select asp-for="CustomerDetails.Subscription" />
                    <abp-input asp-for="CustomerDetails.Remark"/>
                </abp-tab>
                <abp-tab title="@L["Other"].Value">
                    @foreach (var propertyInfo in @Model.CustomerDetails.CustomExtraPropertySetting)
                    {
                        if (Model.CustomerDetails.ExtraProperties.ContainsKey(propertyInfo.CustomPropertyName))
                        {
                            var inputType = String.Empty;
                            var inputFormat = String.Empty;

                            if (@propertyInfo.CustomPropertyType == "datetime")
                            {
                                inputType = "datetime-local";
                                inputFormat = "{0:yyyy-MM-ddTHH:mm}";

                                <abp-input type="@inputType" asp-format="@inputFormat" label="@L[propertyInfo.CustomPropertyName].Value"
                                           asp-for="CustomerDetails.ExtraProperties[propertyInfo.CustomPropertyName]"
                                           value="@String.Format(inputFormat, @Model.CustomerDetails.GetProperty(propertyInfo.CustomPropertyName))" />
                            }
                            else if (@propertyInfo.CustomPropertyType == "bool")
                            {
                                inputType = "checkbox";

                                <abp-input type="@inputType" asp-format="@inputFormat" label="@L[propertyInfo.CustomPropertyName].Value"
                                           asp-for="CustomerDetails.ExtraProperties[propertyInfo.CustomPropertyName]" />
                            }
                            else
                            {
                                if (@propertyInfo.CustomPropertyType == "string")
                                    inputType = "text";
                                else if (@propertyInfo.CustomPropertyType == "int")
                                    inputType = "number";

                                <abp-input type="@inputType" asp-format="@inputFormat" label="@L[propertyInfo.CustomPropertyName].Value"
                                           asp-for="CustomerDetails.ExtraProperties[propertyInfo.CustomPropertyName]"
                                           value="@Model.CustomerDetails.GetProperty(propertyInfo.CustomPropertyName)" />
                            }
                        }
                    }
                </abp-tab>
            </abp-tabs>
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</form>

src/Linkbot.Web/Pages/Customers/Index.cshtml
@page
@using Linkbot.Localization
@using Linkbot.Permissions
@using Linkbot.Web.Pages.Customers
@using Microsoft.AspNetCore.Authorization
@using Microsoft.Extensions.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@model IndexModel
@inject IStringLocalizer<LinkbotResource> L
@inject IAuthorizationService AuthorizationService
@section scripts
{
    <abp-script src="/Pages/Customers/Index.js" />
}

<abp-card id="CustomerDetailsWrapper">
    <abp-card-header>
        <abp-row>
            <abp-column size-md="_6">
                <abp-card-title>@L["Customers"]</abp-card-title>
            </abp-column>
            <abp-column size-md="_4" style="padding:0px">
                <form method="POST" enctype="multipart/form-data" asp-page-handler="Import">
                    <div class="input-group" style="height:30px">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="excel">
                            <label class="custom-file-label col-form-label-sm" for="inputGroupFile02" style="height:30px">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span id=""><abp-button button-type="Primary" type="Submit">Import</abp-button></span>
                        </div>
                    </div>
                </form>
            </abp-column>
            <abp-column size-md="_2" style="padding-left:0px" class="text-right">
                @if (await AuthorizationService.IsGrantedAsync(LinkbotPermissions.Customers.Create))
                {
                    <abp-button id="NewCustomerButton"
                                text="@L["NewCustomer"].Value"
                                icon="plus"
                                button-type="Primary" />
                }
            </abp-column>
        </abp-row>
    </abp-card-header>
    <abp-card-body>
        <abp-row>
            <abp-column size-md="_8"></abp-column>
            <abp-column size-md="_3" style="padding-right:0px">
                <form id="CustomersFilterForm" method="post" class="page-search-form">
                    <div class="input-group">
                        <input class="form-control page-search-filter-text form-control-sm" placeholder="@L["Search"].Value" asp-for="Filter" />
                        <abp-button button-type="Primary" type="submit" size="Small" >
                            <i class="fa fa-search" aria-hidden="true"></i>
                        </abp-button>
                    </div>
                </form>
            </abp-column>
            <abp-column size-md="_1">
                <div class="input-group">
                    <div>
                        <form id="CustomersExportForm" method="POST" asp-page-handler="Export">
                            <input type="hidden" asp-for="FilterHidden" value="" />
                            <abp-button size="Small" button-type="Primary" type="Submit">Export</abp-button>
                        </form>
                    </div>
                </div>
            </abp-column>
        </abp-row>
        <abp-table striped-rows="true" id="CustomersTable"></abp-table>
    </abp-card-body>
</abp-card>

<abp-modal id="UpcomingApptModal" size="Large">
    <abp-modal-header title="@L["UpcomingAppointment"].Value"></abp-modal-header>
    <abp-modal-body>
        <abp-table striped-rows="true" id="UpcomingApptTable"></abp-table>
    </abp-modal-body>
    <abp-modal-footer buttons="@(AbpModalButtons.Close)"></abp-modal-footer>
</abp-modal>

<abp-modal id="PurchaseHistoryModal" size="Large">
    <abp-modal-header title="@L["PurchaseHistory"].Value"></abp-modal-header>
    <abp-modal-body>
        <abp-table striped-rows="true" id="PurchaseHistoryTable"></abp-table>
    </abp-modal-body>
    <abp-modal-footer buttons="@(AbpModalButtons.Close)"></abp-modal-footer>
</abp-modal>